spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: http://order-service:8081
          predicates:
            - Path=/orders/**
        - id: inventory-service
          uri: http://inventory-service:8082
          predicates:
            - Path=/inventory/**
server:
  port: 8080
springdoc:
  swagger-ui:
    enabled: true
    path: '/swagger-ui'
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,swagger