apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: yourdockerhub/order-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "local"
            - name: DB_URL
              value: "jdbc:postgresql://postgres:5432/orderdb"
            - name: ORDER_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: backend
                  key: ORDER_DB_USERNAME
            - name: ORDER_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend
                  key: ORDER_DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081