spring:
  application:
    name: order-service
  datasource:
#    url: jdbc:postgresql://localhost:5432/orderdb
    url: jdbc:postgres://localhost:5432/orderdb
    username: ${ORDER_DB_USERNAME}
    password: ${ORDER_DB_PASSWORD}
    driver-class-name: 'org.postgresql.Driver'
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    user: ${ORDER_DB_USERNAME}
    password: ${ORDER_DB_PASSWORD}
#    url: jdbc:postgresql://localhost:5432/orderdb
    url: jdbc:postgresql://postgres:5432/orderdb

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,swagger

resilience4j:
  circuitbreaker:
    instances:
      inventoryService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50