spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://localhost:5432/inventorydb
    username: ${INVENTORY_DB_USERNAME}
    password: ${INVENTORY_DB_PASSWORD}
    driver-class-name: 'org.postgresql.Driver'
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    user: ${INVENTORY_DB_USERNAME}
    password: ${INVENTORY_DB_PASSWORD}
    url: jdbc:postgresql://localhost:5432/inventorydb

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,swagger